const {chromium}=require('./runtime.cjs').dependency('playwright');
const fs=require('node:fs/promises');
const assert=require('node:assert/strict');
const url=process.argv[2]||'http://127.0.0.1:43821/';const tag=process.argv[3]||'local';
(async()=>{
 const browser=await chromium.launch(require('./runtime.cjs').launchOptions());
 const report={url,date:new Date().toISOString(),viewports:[],checks:[],errors:[],networkErrors:[],responsiveImageCancellations:[]};
 const context=await browser.newContext({reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.networkErrors.push({url:r.url(),status:r.status()})});page.on('requestfailed',r=>{const failure={url:r.url(),error:r.failure().errorText};if(failure.error==='net::ERR_ABORTED'&&failure.url.includes('/assets/region-'))report.responsiveImageCancellations.push(failure);else report.networkErrors.push(failure)});
 for(const [width,height] of [[1440,1000],[768,1024],[390,844],[320,740]]){
  await page.goto('about:blank');await page.setViewportSize({width,height});await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
  const state=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,imageLoaded:[...document.images].every(i=>i.complete&&i.naturalWidth>0),image:document.images[0].currentSrc,fonts:document.fonts.check('700 32px "Barlow Condensed"')&&document.fonts.check('400 16px "DM Sans"'),overflow:[...document.querySelectorAll('main *,header *,footer *')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+1||r.left< -1)}).map(e=>e.tagName+'.'+e.className)}));
  assert.equal(state.scrollWidth,width,'horizontal overflow at '+width);assert(state.imageLoaded,'images at '+width);assert(state.fonts,'fonts at '+width);assert.equal(state.overflow.length,0,'elements out of viewport '+JSON.stringify(state.overflow));
  await page.screenshot({path:`qa-artifacts/${tag}-${width}-full.png`,fullPage:true});await page.screenshot({path:`qa-artifacts/${tag}-${width}-hero.png`});report.viewports.push({width,viewportHeight:height,...state});
 }
 report.checks.push('No horizontal overflow; images and both local font families loaded at 320, 390, 768, 1440px');
 const structure=await page.evaluate(()=>({h1:document.querySelectorAll('h1').length,robots:document.querySelector('meta[name=robots]').content,missingLabels:[...document.querySelectorAll('input,select,textarea')].filter(e=>!document.querySelector(`label[for="${e.id}"]`)).length,badAnchors:[...document.querySelectorAll('a[href^="#"]')].filter(a=>a.hash&&!document.querySelector(a.hash)).map(a=>a.hash),phones:[...document.querySelectorAll('a[href^="tel:"]')].map(a=>a.getAttribute('href')),emails:[...document.querySelectorAll('a[href^="mailto:"]')].map(a=>a.getAttribute('href')),emDash:document.body.innerText.includes('—'),schema:JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent)['@type'],motion:getComputedStyle(document.documentElement).scrollBehavior}));
 assert.equal(structure.h1,1);assert.equal(structure.robots,'noindex, nofollow');assert.equal(structure.missingLabels,0);assert.deepEqual(structure.badAnchors,[]);assert(structure.phones.every(x=>x==='tel:+14232207705'));assert(structure.emails.every(x=>x.startsWith('mailto:eartheffectstn@gmail.com')));assert.equal(structure.emDash,false);assert.equal(structure.schema,'WebPage');assert.equal(structure.motion,'auto');report.checks.push('Semantic headings, labels, anchors, phone/email, noindex, JSON-LD and reduced motion verified');
 await page.goto(url,{waitUntil:'networkidle'});await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Skip to content');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#main');report.checks.push('Keyboard skip link works; focus outline present');
 await page.locator('[data-service="Landscape maintenance"]').click();assert.equal(await page.locator('#service').inputValue(),'Landscape maintenance');await page.locator('#prepare-request').click();assert.equal(await page.locator('#request-review').isVisible(),false);
 await page.locator('#name').fill('Pat & Taylor');await page.locator('#email').fill('not-an-email');await page.locator('#description').fill('Unicoi property. Lawn & beds need attention.\nPlease discuss upkeep.');await page.locator('#prepare-request').click();assert.equal(await page.locator('#request-review').isVisible(),false);
 await page.locator('#email').fill('preview-test@example.com');await page.locator('#phone').fill('423-555-0123');const beforeRequests=[];page.on('request',r=>beforeRequests.push({method:r.method(),url:r.url()}));await page.locator('#prepare-request').click();assert(await page.locator('#request-review').isVisible());assert.equal(await page.locator('#quote-form').isVisible(),false);assert.equal(await page.locator(':focus').getAttribute('id'),'review-title');const href=await page.locator('#email-draft').getAttribute('href');const parsed=new URL(href);const body=parsed.searchParams.get('body');assert(body.includes('Pat & Taylor'));assert(body.includes('Lawn & beds'));assert(body.includes('\nPlease discuss upkeep.'));assert.equal(parsed.searchParams.get('subject'),'Free quote request: Landscape maintenance');assert.equal(beforeRequests.filter(x=>/^https?:/.test(x.url)).length,0,'form must not send a network request');await page.screenshot({path:`qa-artifacts/${tag}-quote-review.png`,fullPage:false});
 await page.locator('#copy-request').click();await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.length>0);assert(/Request copied|Copy the selected text/.test(await page.locator('#copy-status').textContent()));await page.locator('#edit-request').click();assert.equal(await page.locator('#name').inputValue(),'Pat & Taylor');assert.equal(await page.locator('#description').inputValue(),'Unicoi property. Lawn & beds need attention.\nPlease discuss upkeep.');
 await page.locator('#name').fill('   ');await page.locator('#prepare-request').click();assert.equal(await page.locator('#request-review').isVisible(),false);await page.locator('#name').fill('<img src=x onerror=alert(1)>');await page.locator('#prepare-request').click();assert(await page.locator('#request-summary').textContent().then(x=>x.includes('<img src=x')));assert.equal(await page.locator('#request-summary img').count(),0);report.checks.push('Service preselect, required/invalid/whitespace validation, encoded multiline draft, safe text rendering, clipboard, editing, and zero network submissions verified');
 await page.goto('about:blank');await page.setViewportSize({width:1440,height:1000});await page.goto(url,{waitUntil:'networkidle'});await page.addStyleTag({content:'html{font-size:200%}'});const zoom=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert.equal(zoom.width,zoom.scrollWidth);report.checks.push('200% text size at desktop has no horizontal overflow');await page.screenshot({path:`qa-artifacts/${tag}-text-200.png`,fullPage:true});
 const noJs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const fallback=await noJs.newPage();await fallback.goto(url);assert(await fallback.locator('noscript').isVisible());assert(await fallback.locator('#prepare-request').isDisabled());report.checks.push('No-JavaScript email/phone fallback works without misleading submission');await noJs.close();
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.networkErrors,[]);await fs.writeFile(`qa-artifacts/${tag}-report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});





